variable "resource_group_name" {}
variable "subnet_id" {}
variable "cluster_name" {}
variable "location" {}
variable "node_count" {}
variable "acr_id" {}
variable "vm_size" {}
variable "kubernetes_version" {}
variable "aks_subnet_prefix" {}
variable "dns_service_ip" {}